services:
  ollama:
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
    environment:
      - OLLAMA_LLM_LIBRARY=rocm
      - HSA_OVERRIDE_GFX_VERSION=8.0.3
      - ROC_ENABLE_PRE_VEGA=1
